version: "3.9"
services:
  client:
    build:
      context: ./client
      ports:
        - "8200:80"
  server:
    build:
      context: ./server
      ports:
        - "7200:7200"
networks:
  app_network:
    driver: bridge
  